name: print_netlify_url
on: [pull_request]
jobs:
  get-netlify-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Netlify
        uses: JakePartusch/wait-for-netlify-action@v1.2
        id: waitFor200
        with:
          site_name: "dhjensen"
          max_timeout: 240
      - name: Print netlify URL
        id: print
        run: echo ${{steps.waitFor200.outputs.url}}
      - name: Add Netlify URL as comment to pull request
        id: addComment
        uses: mshick/add-pr-comment@v1
        with:
          message: ${{steps.waitFor200.outputs.url}}
          allow-repeats: true